### ISSUE TITLE
Ambiguïté des encarts jaunes

### ISSUE THREAD

**Issue by ipante** [Marylou1998/Fiction-Interactive-SA22#4]
Le premier encart jaune semble être un "call to action" (j'ai cliqué dessus).
Cette mise en évidence n'est pas immédiatement claire : j'ai d'abord pensé qu'il s'agissait d'un message du bourreau. Peut-être pourriez-vous clarifier en remplaçant l'encart jaune par une bulle (genre bulle de messagerie).

**Comment by Marylou1998** [comment]
Résolu : en utilisant un encadré similaire au nouvel encadré des notifications sms. Pour les notifications où on ne peut faire aucune action, l'encadré est gris (lorsqu'on reçoit / envoie un message sans pouvoir en changer le contenu). Lorsqu'on peut faire une action, l'encadré est jaune (entrer code, entrer nom, entrer le message d'alerte à Sophie).
