### ISSUE TITLE
Formulation

### ISSUE THREAD

**Issue by ipante** [Marylou1998/Fiction-Interactive-SA22#5]
Avez-vous pris le bon choix ? => Avez-vous fait le bon choix ?

**Comment by ipante** [comment]
Vous avez mal dormis => mal dormi

**Comment by ipante** [comment]
comptoire => comptoir

**Comment by ipante** [comment]
nom de code : vas chier => va chier

**Comment by ipante** [comment]
il se park => il se parque

**Comment by ipante** [comment]
Il y a un flottement entre le tu et le vous dans les dernières recommandations : il faut uniformiser (Lorsque **tu** sens que la tension monte, tenez-**vous** près d’une porte de sortie...)

**Comment by Marylou1998** [comment]
heureusement que j'avais prévu qu'il y aurait des fautes d'orthographe en écrivant mon nom de code...
