### ISSUE TITLE
Environnement sonore

### ISSUE THREAD

**Issue by ipante** [Marylou1998/Fiction-Interactive-SA22#6]
Quatre morceaux de musique ajouteraient de l'ampleur à votre récit. Le premier pour l'angoisse initiale, le second pour la tension maximale (avant de partir) le troisième pour la résolution négative et le quatrième pour la résolution négative.

**Comment by Marylou1998** [comment]
Environnement sonore ajouté : 
- bruit d'horloge tout au long de la fiction en background.
- une musique pour la première partie lorsque le joueur est coincé dans le cycle. 
- Bruit de respiration dès le second tour (back to start)
- Bruits d'achievement + de notification
- Bruit de respiration effrayée lorsque $joueur brise le cycle
- Battements de coeur lorsque la situation devient dangereuse/stressante
- Battements de coeur accélérés à la tension maximale
- Bruit de "countdown" lorsque $joueur doit se dépêcher
- Résolution négative : musique initiale
- Résolution positive (adapter encore le texte) : bruit de voiture qui démarre
